[package]
name = "lnx-query"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
sqlparser = { workspace = true }
tantivy = { workspace = true }
serde_json = { workspace = true }
poem-openapi = { workspace = true }
tracing = { workspace = true }